// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtxdvozolqrqwreajodb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0eGR2b3pvbHFycXdyZWFqb2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjQzNTYsImV4cCI6MjA2MDgwMDM1Nn0.fIWH2HYLjO8ony-uxAWnfh6CNMfMKAgOU9CHFzRpT9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);